[package]
name = "femtofont"
version = "0.5.0"
authors = ["Iris Webb <oliverwebb8192@gmail.com>", "Joe Cumbo <mooman219@gmail.com>"]
license = "MIT OR Apache-2.0 OR Zlib"
documentation = "https://docs.rs/femtofont"
homepage = "https://github.com/iriswebb/femtofont"
repository = "https://github.com/iriswebb/femtofont"
description = "A simple no_std font parser and rasterizer."
keywords = ["font", "text", "truetype", "opentype", "ttf"]
categories = ["no-std", "gui"]
readme = "README.md"
edition = "2021"
exclude = ["dev/**"]

[dependencies]
ttf-parser = { version = "0.25.1", default-features = false, features = [
    "opentype-layout", "no-std-float", "variable-fonts"
] }

[dev-dependencies]
freetype-rs = { version = "0.26.0" }
criterion = "0.3"
rusttype = "0.9.2"
ab_glyph = "0.2"
glyph_brush_layout = "0.2.0"
png = "0.16"
walkdir = "2.3"

[[bench]]
name = "rasterize"
harness = false

[[bench]]
name = "layout"
harness = false

[[bench]]
name = "load"
harness = false
